name = "packverify"
main = "worker/index.ts"
compatibility_date = "2024-12-10"

[[d1_databases]]
binding = "DB"
database_name = "packverify-db"
database_id = "92e4bc51-320d-4198-bdd8-4fcd39beebec"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "packverify-images"

[vars]
FIREBASE_PROJECT_ID = "packyverify"

[build]
command = "npm run build"

[assets]
directory = "./dist"
